#!/usr/bin/env python3
import sys
import yaml
import argparse
from pathlib import Path


def check_file_exists(file_path, description):
    """Check if a file exists and print status."""
    if file_path.exists():
        print(f"  ✓ {description}: {file_path}")
        return True
    else:
        print(f"  ✗ {description}: {file_path} (NOT FOUND)")
        return False


def check_prerequisites(project_path):
    """Check if all required files exist."""
    print("\nChecking required files...")
    errors = []

    # Check required files
    project_yaml = project_path / "project.yaml"
    abstract_draft = project_path / "abstract_draft.md"
    methods_draft = project_path / "methods_draft.md"
    results_draft = project_path / "results_draft.md"

    if not check_file_exists(project_yaml, "project.yaml"):
        errors.append(f"Missing: {project_yaml}")
    if not check_file_exists(abstract_draft, "abstract_draft.md"):
        errors.append(f"Missing: {abstract_draft}")
    if not check_file_exists(methods_draft, "methods_draft.md"):
        errors.append(f"Missing: {methods_draft}")
    if not check_file_exists(results_draft, "results_draft.md"):
        errors.append(f"Missing: {results_draft}")

    return errors


def read_section_content(file_path, section_title):
    """Read section content and remove duplicate top-level heading if present."""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read().strip()

    # Check if first line is the duplicate heading
    lines = content.split("\n")
    if lines and lines[0].strip() == f"# {section_title}":
        # Remove the first line (duplicate heading)
        content = "\n".join(lines[1:]).strip()

    return content


def assemble_manuscript(project_path):
    """Assemble manuscript from section drafts."""
    # Read project name
    project_yaml_path = project_path / "project.yaml"
    with open(project_yaml_path, "r", encoding="utf-8") as f:
        project_data = yaml.safe_load(f)

    project_name = project_data.get("project_name", "Untitled Project")

    # Read section contents
    abstract_content = read_section_content(project_path / "abstract_draft.md", "Abstract")
    methods_content = read_section_content(project_path / "methods_draft.md", "Methods")
    results_content = read_section_content(project_path / "results_draft.md", "Results")

    # Assemble manuscript
    manuscript = f"""<!--
Auto-assembled manuscript V1
Generated by SCIWriter

Status:
- ✓ Abstract: completed
- ✓ Methods: completed
- ✓ Results: completed
- ✗ Title: to be generated
- ✗ Introduction: to be generated
- ✗ Discussion: to be generated

Project: {project_name}
-->

# Title

[To be generated]

# Abstract

{abstract_content}

# Methods

{methods_content}

# Results

{results_content}

# Discussion

[To be generated]
"""

    return manuscript


def main():
    parser = argparse.ArgumentParser(
        description="Assemble manuscript from section drafts",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example usage:
  python3 assemble_manuscript.py --project /path/to/your/project

This will generate manuscript_v1.md from existing section drafts.
        """
    )
    parser.add_argument("--project", required=True, help="Project directory path")
    args = parser.parse_args()

    project_path = Path(args.project).resolve()

    print("=" * 60)
    print("SCIWriter - Manuscript Assembler")
    print("=" * 60)
    print(f"Project: {project_path}")

    # Check prerequisites
    errors = check_prerequisites(project_path)

    if errors:
        print("\n" + "=" * 60)
        print("PREREQUISITE CHECK FAILED")
        print("=" * 60)
        print("\nMissing files:")
        for error in errors:
            print(f"  - {error}")
        print("\nPlease ensure you have generated all section drafts:")
        print("  - abstract_draft.md")
        print("  - methods_draft.md")
        print("  - results_draft.md")
        sys.exit(1)

    print("\n✓ All prerequisite checks passed")

    # Assemble manuscript
    print("\n" + "=" * 60)
    print("ASSEMBLING MANUSCRIPT")
    print("=" * 60)

    manuscript = assemble_manuscript(project_path)
    output_path = project_path / "manuscript_v1.md"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(manuscript)

    print(f"\n✓ Generated: {output_path}")

    # Success summary
    print("\n" + "=" * 60)
    print("ASSEMBLY COMPLETED SUCCESSFULLY")
    print("=" * 60)

    print("\nGenerated file:")
    print(f"  {output_path}")

    print("\nManuscript structure:")
    print("  - Title (placeholder)")
    print("  - Abstract (from abstract_draft.md)")
    print("  - Methods (from methods_draft.md)")
    print("  - Results (from results_draft.md)")
    print("  - Discussion (placeholder)")

    print("\nNext steps:")
    print(f"  1. Review the manuscript: cat {output_path}")
    print("  2. Generate Title and Introduction sections")
    print("  3. Generate Discussion section")
    print("  4. Refine and polish the manuscript")


if __name__ == "__main__":
    main()
